# Generated by Django 6.0.2 on 2026-04-17 19:42

import django.db.models.deletion
from django.db import migrations, models


def create_hypertable(apps, schema_editor):
    """
    Convierte gps_gpspoint en hypertable de TimescaleDB.
    Si TimescaleDB no está disponible (ej. entorno de pruebas)
    la operación se omite sin romper la transacción activa.
    """
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        try:
            # Necesitamos un savepoint para poder hacer rollback parcial
            cursor.execute("SAVEPOINT sp_timescaledb;")
            cursor.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")
            cursor.execute(
                "SELECT create_hypertable('gps_gpspoint', 'timestamp', if_not_exists => TRUE);"
            )
            cursor.execute("RELEASE SAVEPOINT sp_timescaledb;")
        except Exception:
            # TimescaleDB no disponible: volvemos al savepoint y continuamos
            cursor.execute("ROLLBACK TO SAVEPOINT sp_timescaledb;")
            cursor.execute("RELEASE SAVEPOINT sp_timescaledb;")


def reverse_hypertable(apps, schema_editor):
    pass  # No hay operación inversa trivial para hypertables


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_vehicle_tracker_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('speed', models.FloatField()),
                ('heading', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField()),
                ('ignition', models.BooleanField(default=False)),
                ('odometer', models.FloatField(default=0.0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='fleet.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='gps_gpspoin_vehicle_f9eed6_idx')],
            },
        ),
        migrations.RunPython(create_hypertable, reverse_hypertable),
    ]
