# Generated by Django 6.0.2 on 2026-04-22 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_tracker_api_key'),
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpspoint',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gps_points', to='fleet.vehicle'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lng', models.FloatField(blank=True, null=True)),
                ('end_lat', models.FloatField(blank=True, null=True)),
                ('end_lng', models.FloatField(blank=True, null=True)),
                ('max_speed', models.FloatField(default=0.0)),
                ('avg_speed', models.FloatField(default=0.0)),
                ('distance_meters', models.FloatField(default=0.0)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', '-start_time'], name='gps_trip_vehicle_ded7e0_idx')],
            },
        ),
    ]
