# Generated by Django 6.0.2 on 2026-04-22 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_alter_gpspoint_vehicle_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpspoint',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='gps.trip'),
        ),
    ]
