# Generated by Django 6.0.2 on 2026-04-24 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_vehicle_tracker_api_key'),
        ('gps', '0003_gpspoint_trip'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('SPEEDING', 'Exceso de Velocidad'), ('IDLE_TOO_LONG', 'Ralentí Excesivo'), ('GEOFENCE_EXIT', 'Salida de Geocerca'), ('OFF_HOURS_USAGE', 'Uso Fuera de Horario')], max_length=50)),
                ('threshold', models.FloatField(help_text='Valor límite (ej. 100 km/h o 15 minutos)')),
                ('cooldown_minutes', models.IntegerField(default=5, help_text='Minutos a esperar antes de volver a disparar esta misma alerta')),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Si es nulo, aplica a toda la flota', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_alert_rules', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('gps_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='gps.gpspoint')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fleet.vehicle')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
