# Generated by Django 6.0.2 on 2026-04-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='schedule_end',
            field=models.TimeField(blank=True, help_text='Fin de horario permitido', null=True),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='schedule_start',
            field=models.TimeField(blank=True, help_text='Inicio de horario permitido', null=True),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='threshold',
            field=models.FloatField(blank=True, help_text='Valor límite (ej. 100 km/h o 15 minutos)', null=True),
        ),
    ]
