# Generated by Django 5.0.14 on 2026-04-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tracker_api_key',
            field=models.CharField(blank=True, help_text='Almacena el hash de la API Key', max_length=128, null=True),
        ),
    ]
