# Generated by Django 6.0.2 on 2026-04-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('shape_type', models.CharField(choices=[('POLYGON', 'Polígono'), ('CIRCLE', 'Círculo')], default='POLYGON', max_length=10)),
                ('coordinates', models.JSONField(blank=True, default=list, help_text='Lista de [lat, lng] para polígonos')),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('radius_meters', models.FloatField(blank=True, help_text='Radio en metros (solo para círculos)', null=True)),
                ('color', models.CharField(default='#3b82f6', help_text='Color hex para visualización', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
